# Generated by Django 3.2 on 2021-05-19 20:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210425_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
